# Generated by Django 3.2 on 2020-12-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nd15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('parlementaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nd15.parlementaire')),
            ],
            options={
                'unique_together': {('parlementaire', 'email')},
            },
        ),
    ]
